In [1]:
class person:
    def __init__(self,fname,lname):
        self.fn=fname
        self.ln=lname
        
    def pn(self):
        print(self.fn," ",self.ln)
        
class st(person):
    pass

s=st("sachin","tendulkar")
s.pn()

sachin   tendulkar


In [30]:
f=open("D://nu.txt","r")
print(f.read())
f.close()

Hello Wellcome to this file 
i will open this file
using  python
woooowwwweeeeeeNow the file Has note contentNow the file Has note content


In [31]:
f=open("D://nu.txt","r")
print(f.read(10))
f.close()

Hello Well


In [32]:
f=open("D://nu.txt","r")
print(f.readline())
f.close()

Hello Wellcome to this file 



In [33]:
fi=open("D://nu.txt","a")
fi.write("Now the file Has note content")
fi.close()

In [34]:
f1=open("D://nu.txt","r")
print(f1.read())
f1.close()

Hello Wellcome to this file 
i will open this file
using  python
woooowwwweeeeeeNow the file Has note contentNow the file Has note contentNow the file Has note contentNow the file Has note content


In [35]:
f1=open("D://nu2.txt","w")
print("File Created")
f1.close()

File Created


In [39]:
f1=open("D://nu2.txt","w")
f1.write("Now the file Has note content")
print("Content written")
f1.close()

Content written


In [38]:
f1=open("D://nu2.txt","r")
print(f1.read())
f1.close()
f.close()

Now the file Has note content


In [2]:
import os
if os.path.exists("D://nu2.txt"):
    os.remove("D://nu2.txt")
    print("File Deleted")

else:
    print("the file doesnt exist")


File Deleted


In [11]:
import datetime as d
x=d.datetime.now()

print("Year is",x.year)
print("Week Day Full version is",x.strftime("%A"))#weekday full version
print("Day is",x.strftime("%w"))#weekday as number
print("Month name full version is",x.strftime("%B"))#month name full version
print("Month as Number",x.strftime("%m"))
print("Month is",x.month)
print("Hour is",x.strftime("%H"))
print("Minute is",x.strftime("%M"))
print("Second is",x.strftime("%S"))
print("Week Number Of year",x.strftime("%U"))
print("locale date time is",x.strftime("%c"))
print("locale date time is",x.strftime("%x"))
print("locale date time is",x.strftime("%X"))

Year is 2022
Week Day Full version is Friday
Day is 5
Month name full version is July
Month as Number 07
Month is 7
Hour is 12
Minute is 12
Second is 28
Week Number Of year 26
locale date time is Fri Jul  1 12:12:28 2022
locale date time is 07/01/22
locale date time is 12:12:28


In [10]:
import datetime as d
dt=d.datetime(1990,5,25)
print("custom date :",dt)

custom date : 1990-05-25 00:00:00


In [15]:
import json
person='{"name":"John","age":30,"city":"Bangalore"}'
y=json.loads(person)
print("Name is ",y["name"])
print("Age is ",y["age"])
print("City is ",y["city"])

data=json.dumps(person)
print(data)

Name is  John
Age is  30
City is  Bangalore
"{\"name\":\"John\",\"age\":30,\"city\":\"Bangalore\"}"


In [18]:
import json

print(json.dumps({"name":"John","age":50}))
print(json.dumps(["Apple","Orange","Banana"]))
print(json.dumps(("Apple","Orange","Banana")))

{"name": "John", "age": 50}
["Apple", "Orange", "Banana"]
["Apple", "Orange", "Banana"]


In [23]:
import re

txt="Its raining in spain"
x=re.search("^Its.*pain$",txt)

if x:
    print("yes! we have a match")
else:
    print("No match")

yes! we have a match


In [24]:
import re
pattern="The rain in spain"
match=re.findall("[a-m]",pattern)
print(match)

pattern1="Hello world";
m=re.findall("^Hello",pattern1)

if m:
    print("yes,the string start with 'hello'")

else:
    print("no match found")

['h', 'e', 'a', 'i', 'i', 'a', 'i']
yes,the string start with 'hello'


In [25]:
import re
pattern="The rain in spain falls mainly in the plain"
match=re.findall("falls|says",pattern)
print(match)



if match:
    print("yes,there is at least one match")

else:
    print("no match found")

['falls']
yes,there is at least one match


In [26]:
import re

pattern="hello world"

m=re.findall("he.{2}o",pattern)
print(m)

['hello']


In [27]:
import re 
pattern ="hello planet"
match=re.findall("he.*o",pattern) 
print(match) 
match1=re.findall("pl.*t",pattern) 
print(match1)

['hello']
['planet']


In [28]:
import re

pattern ="The rain in spain"
match=re.findall("\AThe",pattern)# A for only checking the first word 
print(match)

if match:
    print("yes,there is a match")
else:
    print("No match")

['The']
yes,there is a match


In [29]:
import re

txt="The rain in spain"
match=re.search("\s",txt)#\s it will search for space

print("the first white-space character is located in position:",match.start())

the first white-space character is located in position: 3


In [30]:
import  re
pattern ="the rain in spain"
match=re.sub("\s","*",pattern)
print(match)

the*rain*in*spain


In [31]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [32]:
#multi dimensional array

import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [33]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [34]:
#datatype parameter

import numpy as np
a=np.array([1,2,3],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]
