In [1]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [3]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np
a=np.arange(24)
print(a)
a.ndim
b=a.reshape(2,4,3)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [7]:
import numpy as np
x=np.zeros((3,2),dtype=[('x','i4'),('y','i4')])
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [8]:
import numpy as np
x=np.zeros((5,),dtype=np.int)
print(x)

[0 0 0 0 0]


C:\Users\shashikiran.m\AppData\Local\Temp\ipykernel_1544\2977770896.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x=np.zeros((5,),dtype=np.int)


In [9]:
#zeros

import numpy as np
x=np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [10]:
#Array Routines

import numpy as np

x=np.empty([3,2],dtype=int)
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
import numpy as np
x=np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [12]:
import numpy as np
x=np.ones([3,3],dtype=int)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [13]:
#converting list into array
import numpy as np
x=[1,2,3,4]
print(type(x))

a=np.asarray(x);
print(a)
print(type(a))

<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [14]:
#converting tuple into array

import numpy as np
x=(1,2,3,4)
print(type(x))

a=np.asarray(x);
print(a)
print(type(a))

<class 'tuple'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [15]:
#converting array from tuple of list

import numpy as np
x=([1,2,3],[4,5])# tuple inside list
print(type(x))

a=np.asarray(x);
print(a)
print(type(a))

<class 'tuple'>
[list([1, 2, 3]) list([4, 5])]
<class 'numpy.ndarray'>


C:\Users\shashikiran.m\AppData\Local\Temp\ipykernel_1544\1588582252.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.asarray(x);


In [16]:
#list of objects
import numpy as np
list=range(5)
it=iter(list)

x=np.fromiter(it,dtype=int)
print(x)

[0 1 2 3 4]


In [18]:
import numpy as np
x=np.arange(10,20,2)
print(x)



[10 12 14 16 18]


In [19]:
#slice demo
import numpy as np
a=np.arange(10)
print(a[2:])

[2 3 4 5 6 7 8 9]


In [20]:
import numpy as np
a=np.arange(10)
s=slice(2,7,2)
print(a[s])

[2 4 6]


In [25]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

#slice items starting from index1

print("now will slice array from the index a[1:]")
print(a[1:])

print("\n")

print("From 2nd coloum")
print(a[...,1])

print("From 3rd Coloumn")
print(a[...,2])


print("From 2nd row")
print(a[1,...])

print("From 3rd row")
print(a[2,...])





[[1 2 3]
 [4 5 6]
 [7 8 9]]
now will slice array from the index a[1:]
[[4 5 6]
 [7 8 9]]


From 2nd coloum
[2 5 8]
From 3rd Coloumn
[3 6 9]
From 2nd row
[4 5 6]
From 3rd row
[7 8 9]


In [26]:
#array iteration

import numpy as np
a=np.arange(0,60,5)
a=a.reshape(3,4)
print("orginal array")
print(a)

print("modified array")
for x in np.nditer(a):
    print(x)

orginal array
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
modified array
0
5
10
15
20
25
30
35
40
45
50
55


In [28]:
import numpy as np
a=np.arange(0,60,5)
a=a.reshape(3,4)
print("orginal array")
print(a)
print("\n")

print('modified array')
for x in np.nditer(a,flags=['external_loop'],order='F'):
    print(x)



orginal array
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


modified array
[ 0 20 40]
[ 5 25 45]
[10 30 50]
[15 35 55]


In [29]:
import numpy as np
a=np.arange(0,60,5)
a=a.reshape(3,4)
print("orginal array")
print(a)
print("\n")

for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=2*x
print('modified array')
print(a)

orginal array
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


modified array
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [30]:
#string function

import numpy as np
print("string concatenation")
print(np.char.add(['hello'],['xyz']))
print("\n")

print("concatenation")
print(np.char.add(['hello','world'],['abc','xyz']))

string concatenation
['helloxyz']


concatenation
['helloabc' 'worldxyz']


In [32]:

#mathematical functions
import numpy as np
a=np.array([0,30,45,60,90])
print("sign of differeny angles")
print(np.sin(a*np.pi/180))
print("\n")
print("cosine values for angles in array")
print(np.cos(a*np.pi/90))
print("Tangent values for angles in array")
print(np.tan(a*np.pi/180))





sign of differeny angles
[0.         0.5        0.70710678 0.8660254  1.        ]


cosine values for angles in array
[ 1.000000e+00  5.000000e-01  6.123234e-17 -5.000000e-01 -1.000000e+00]
Tangent values for angles in array
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [33]:

#round function
import numpy as np
a=np.array([1.0,5,55,123,0,567,25,532])
print("orginal array")
print(np.round(a))
print(np.round(a,decimals=1))
print(np.round(a,decimals=-1))

orginal array
[  1.   5.  55. 123.   0. 567.  25. 532.]
[  1.   5.  55. 123.   0. 567.  25. 532.]
[  0.   0.  60. 120.   0. 570.  20. 530.]


In [34]:
#floor function

import numpy as np
a=np.array([-1.7,1.5,-0.2,0.6,10])
print("orginal array")
print(np.floor(a))

orginal array
[-2.  1. -1.  0. 10.]


In [35]:
# ceil function

import numpy as np
a=np.array([-1.7,1.5,-0.2,0.6,10])
print("orginal array")
print(np.ceil(a))

orginal array
[-1.  2. -0.  1. 10.]


In [36]:
def fun1(num1):
    try:
        reci=1/num1;

    except ZeroDivisionError:
        print("we cannot divide by zero")

    else:
        print(reci)

fun1(4)

fun1(0)

0.25
we cannot divide by zero


In [37]:
try:
    print("hi")
    print("hello")
    print(9/0);

except ZeroDivisionError:
        print("we cannot divide by zero")

print(9/3)
print("welcome")

hi
hello
we cannot divide by zero
3.0
welcome


In [41]:
y=100
try:
    print(y)
except NameError:
    print("variable y is not defined")
else:
    print("something went wrong")

100
something went wrong
